# update user password
- name: Change user password
  user: name={{ item.name }} password={{ item.chpass | password_hash('sha512') }}  update_password=always
  with_items:
           - { name: 'root', chpass: 'P@ssw0rd' }
