- name: Set up static IP address
  win_shell: "Set-NetIPAddress -InterfaceIndex 8 -IPAddress 10.2.14.116 Set-NetIPInterface -InterfaceAlias Ethernet0  -DefaultGatewayi 10.2.14.254"
  async: 100 # Using "fire-and-forget" asynchronous execution for this task, otherwise it will always fail and timeout
  poll: 0

